FROM python:3.12-slim

WORKDIR /app

RUN pip install poetry

COPY pyproject.toml poetry.lock ./

RUN poetry config virtualenvs.create false && poetry install --no-root

COPY . . 

EXPOSE 3000

CMD ["poetry", "run", "uvicorn", "app:app", "--host", "0.0.0.0", "--port", "3000"]

