version: "3.8"

services:
  app:
    build: .
    container_name: "tarefas-api"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file:
      - .env
    command: ["poetry", "run", "uvicorn", "app:app", "--host", "0.0.0.0", "--port", "3000"]